apiVersion: v1
kind: Service
metadata:
  name: {{ include "hextris.name" . }}-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "hextris.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
  selector:
    app: {{ include "hextris.name" . }}