apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: hextris
spec:
  selector:
    app: hextris
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
